name: Blockchain
channels:
  - conda-forge
  - defaults
dependencies:
  - blinker=1.7.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py38hd3f51b4_1
  - bzip2=1.0.8=hcfcfb64_5
  - ca-certificates=2023.11.17=h56e8100_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - flask=3.0.0=pyhd8ed1ab_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - libffi=3.4.2=h8ffe710_5
  - libsqlite=3.44.2=hcfcfb64_0
  - libzlib=1.2.13=hcfcfb64_5
  - markupsafe=2.1.3=py38h91455d4_1
  - openssl=3.2.0=hcfcfb64_1
  - pip=23.3.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.8.18=h4de0772_1_cpython
  - python_abi=3.8=4_cp38
  - requests=2.31.0=pyhd8ed1ab_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=2.1.0=pyhd8ed1ab_0
  - vc=14.3=hcf57466_18
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - werkzeug=3.0.1=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xz=5.2.6=h8d14728_0
  - zipp=3.17.0=pyhd8ed1ab_0
prefix: C:\Users\albam\anaconda3\envs\Blockchain
